# -*- coding: utf-8 -*-
"""The Brewery Project Web Scraping (Metro).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGAJKrDj-6lGb_TDo-NLdSjOgDc1rjxS
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://worldpopulationreview.com/us-cities"
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

metroCitiesGroup = soup.find_all('table', class_='tp-table-body is-narrow w-full min-w-full table-auto border-separate border-spacing-0 border bg-white')
metroCitiesGroup = metroCitiesGroup[1]
print(metroCitiesGroup)
metroCities = metroCitiesGroup.find_all("tr",class_="odd:bg-white even:bg-gray-100")
#print(metroCities[10])

cityNames = []
ranks = []
stateNames = []
totalPopulations = []

for city in metroCities:
    cityName = city.find('a').get_text()
    cityDetails = city.find_all('td', class_="z-40 border px-2 py-0.5")
    cityRank = cityDetails[0].get_text()
    cityPopulation = cityDetails[1].get_text()
    cityStateTxt = city.find('a')['href'].split("-population")[0][-2:]
    if cityName and cityRank:
        cityNames.append(cityName)
        ranks.append(cityRank)
        stateNames.append(cityStateTxt)
        totalPopulations.append(cityPopulation)

dict = {'City Names': cityNames, 'Rank': ranks,"State": stateNames, '2024 Population': totalPopulations}
metroData = pd.DataFrame(dict)
metroData

metroData.info()

metroData.info()

metroData.dtypes

#Fix Data Types:
#Particulatly the population column to be integer
for i in range(0,len(metroData["2024 Population"])):
    popNumeric = int(metroData["2024 Population"][i].replace(",",""))
    metroData["2024 Population"][i] = popNumeric
    metroData["Rank"][i] = int(metroData["Rank"][i])

#Fix Data:
#Capitalize States
for i in range(0,len(metroData["State"])):
    stateCaps = metroData["State"][i].upper()
    metroData["State"][i] = stateCaps

#Merge in region data to metroData
regions = pd.read_csv('https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv')
regions = pd.DataFrame(regions)
regions

metroData = metroData.merge(regions, left_on='State', right_on='State Code')
metroData = metroData.sort_values(by = ["Rank"])
metroData = metroData.drop(["State Code"], axis = 1)
metroData = metroData.rename(columns={"State_x": "State Code", "State_y": "State Name"})

metroData

#Export metroData as .csv
metroData.to_csv('metropolianCities.csv')