# -*- coding: utf-8 -*-
"""The Brewery Project Web Scraping (Tech).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13uYpDOY4i638Gkccu7iqvR_r48p8RgIp
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.zdnet.com/education/computers-tech/top-tech-hubs-in-the-us/"
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

techCities = soup.find_all('h3')
#print(techCities[0])

cityState = []

for city in techCities:
    cityName = city.get_text()
    if cityName:
        cityState.append(cityName)

techData = pd.DataFrame(cityState)
techData = techData.rename(columns={0: "City, State"})

# techData.head(10) #Uncleaned Data # commented out by CK for script running

#Cleaning:
#Split city and state on ","
techData[["City","State"]]= techData["City, State"].str.split(pat = ', ',expand = True)

techData = techData.drop(["City, State"], axis = 1)# Removes unnecessary columns

# techData.info() # commented out by CK for script running

#Notice Dallas-Fort Worth do not have Texas as the associated state.
#Remove this combined row and append to records for the separate cities

techData = techData.drop([9], axis = 0)
updatedCities = pd.DataFrame([["Dallas", "TX"],["Fort Worth","TX"]], columns = ["City","State"])
techData = pd.concat([techData,updatedCities], ignore_index = True)

#Trim spaces off of state codes
for i in range(0,len(techData["State"])):
    stateClean = techData["State"][i][:2]#Remove hidden character at end of state
    techData["State"][i] = stateClean

#Merge in region data to metroData
regions = pd.read_csv('https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv')
regions = pd.DataFrame(regions)
regions.head()

techData = techData.merge(regions, left_on='State', right_on='State Code')
techData = techData.drop(["State Code"], axis = 1)
techData = techData.rename(columns={"State_x": "State Code", "State_y": "State Name"})

# techData.head() # commented out by CK for script running

#Export techData as .csv
techData.to_csv('../data/techHubs.csv')