# -*- coding: utf-8 -*-
"""The Brewery Project Web Scraping (Census).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNvShkOB-VObOXegO4wAfT75ZyJlpYho
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import urllib.request

url = "https://api.census.gov/data/2020/dec/dp?get=NAME,DP1_0001C,DP1_0022P,DP1_0024P,DP1_0025C,DP1_0049C,DP1_0086P,DP1_0087P,DP1_0088P,DP1_0089P,DP1_0090P,DP1_0091P,DP1_0093P&for=place:*&in=state:*"
response = requests.get(url)

#About the variables: https://api.census.gov/data/2020/dec/dp/variables.html

data = response.json()

array = []
for row in data:
  array.append(row)

array = array[1:]

censusData = pd.DataFrame(array, columns = ["City, State","Total Population",
                                            "% age 21+","% age 65+","Total Men",
                                            "Total Women","% Race - White",
                                            "% Race - Black","% Race - American Native",
                                            "% Race  - Asian","% Race - Pacific Islander",
                                            "% Race - Other","% Race - Hispanic/Latino",
                                            "state","place"])

censusData[["Total Population","Total Men","Total Women"]] = censusData[["Total Population","Total Men","Total Women"]].apply(pd.to_numeric)
censusData[[ "% age 21+","% age 65+","% Race - White", "% Race - Black",
           "% Race - American Native","% Race  - Asian","% Race - Pacific Islander",
            "% Race - Other","% Race - Hispanic/Latino"]] = censusData[["% age 21+",
            "% age 65+","% Race - White", "% Race - Black",
           "% Race - American Native","% Race  - Asian","% Race - Pacific Islander",
            "% Race - Other","% Race - Hispanic/Latino"]].apply(pd.to_numeric)
print(censusData.dtypes)
censusData["% Male"] = censusData["Total Men"]/ censusData["Total Population"]
censusData = censusData.drop(["state","place", "Total Men", "Total Women"], axis = 1)

censusData.head()

url = "https://api.census.gov/data/2021/acs/acs1?get=NAME,B06011_001E&for=place:*"
response = requests.get(url)

data = response.json()

array = []
for row in data:
  array.append(row)

array = array[1:]

incomeData = pd.DataFrame(array, columns = ["City, State","2021 Median Income","state","place"])
incomeData = incomeData.drop(["state","place"], axis = 1)

incomeData.head()

censusData = censusData.merge(incomeData, on= "City, State")

#need to remove town, city, CDP designation from "City, State"

censusData['City, State'] = censusData['City, State'].str.replace(' city,', ",")
censusData['City, State'] = censusData['City, State'].str.replace(' CDP,', ",")
censusData['City, State'] = censusData['City, State'].str.replace(' town,', ",")
censusData.head()

#Export censusData as .csv
censusData.to_csv('censusData.csv')